name: CI/CD

on:
  - push
  - pull_request

env:
  RYE_INSTALL_OPTION: --yes

jobs:
  test:
    name: Test

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye-up.com/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Execute tests
        run: |
          rye sync
          rye run test

  check:
    name: Check

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye-up.com/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Install dependencies
        run: rye sync

      - name: Check
        run: rye run check
